// Motion bank for debat ppl.
//
// Entries are [motion, region, theme]. Motions are written the way the activity is
// actually run: "This House ..." for the worlds-style circuits (WUDC, EUDC, Australs,
// UADC, WSDC, Pan-African, All-Asians) and "Resolved: ..." for the NSDA-style ones,
// which live in RESOLUTIONS at the bottom.
//
// Regions: GLOBAL AFR MENA EUR NAM LAM CARIB SAS EAS SEA CAS OCE
// Themes:  pol econ env tech ai law edu health media ethics gender war culture
//          sport dev relig space labour urban youth mig

export const REGIONS = {
  GLOBAL: "International",
  AFR: "Africa",
  MENA: "Middle East & North Africa",
  EUR: "Europe",
  NAM: "North America",
  LAM: "Latin America",
  CARIB: "Caribbean",
  SAS: "South Asia",
  EAS: "East Asia",
  SEA: "Southeast Asia",
  CAS: "Central Asia & Caucasus",
  OCE: "Oceania",
};

export const THEMES = {
  pol: "Politics & governance",
  econ: "Economics",
  env: "Environment",
  tech: "Technology",
  ai: "Artificial intelligence",
  law: "Law & criminal justice",
  edu: "Education",
  health: "Health",
  media: "Media",
  ethics: "Ethics & philosophy",
  gender: "Gender & family",
  war: "War & security",
  culture: "Culture & the arts",
  sport: "Sport",
  dev: "Development",
  relig: "Religion",
  space: "Space",
  labour: "Labour",
  urban: "Cities & housing",
  youth: "Children & youth",
  mig: "Migration",
};

export const MOTIONS = [
  // --- International institutions, order and conflict -----------------------
  ["This House would abolish the veto power of the permanent members of the UN Security Council", "GLOBAL", "pol"],
  ["This House would give permanent Security Council seats to the African Union and India", "GLOBAL", "pol"],
  ["This House believes that the International Criminal Court should prosecute sitting heads of state", "GLOBAL", "law"],
  ["This House regrets the growth of minilateral blocs at the expense of universal institutions", "GLOBAL", "pol"],
  ["This House would create a standing United Nations rapid reaction force", "GLOBAL", "war"],
  ["This House would make ecocide a crime under the Rome Statute", "GLOBAL", "env"],
  ["This House would abolish investor-state dispute settlement", "GLOBAL", "econ"],
  ["This House believes that heavily indebted states should coordinate a collective default", "GLOBAL", "econ"],
  ["This House would allow states to trade their refugee resettlement quotas", "GLOBAL", "mig"],
  ["This House supports a binding international treaty on climate loss and damage", "GLOBAL", "env"],
  ["This House believes that humanitarian intervention without Security Council authorisation is legitimate", "GLOBAL", "war"],
  ["This House would ban the export of surveillance technology to non-democracies", "GLOBAL", "tech"],
  ["This House believes that sanctions regimes targeting whole economies are immoral", "GLOBAL", "war"],
  ["This House would create an international court with jurisdiction over multinational corporations", "GLOBAL", "law"],
  ["This House believes that the Non-Proliferation Treaty has outlived its usefulness", "GLOBAL", "war"],
  ["This House would prohibit the development of lethal autonomous weapons systems", "GLOBAL", "war"],
  ["This House believes that peacekeeping missions should be permitted to use offensive force", "GLOBAL", "war"],
  ["This House would require wealthy states to accept climate migrants in proportion to their historic emissions", "GLOBAL", "mig"],
  ["This House regrets the dominance of English in international institutions", "GLOBAL", "culture"],
  ["This House would abolish diplomatic immunity for serious criminal offences", "GLOBAL", "law"],
  ["This House believes that truth and reconciliation commissions are preferable to criminal trials after mass atrocity", "GLOBAL", "law"],
  ["This House would recognise statehood on the basis of popular referendum alone", "GLOBAL", "pol"],
  ["This House believes that small island states should be permitted to retain statehood after their territory is submerged", "GLOBAL", "env"],
  ["This House would create a global minimum wealth tax collected by an international body", "GLOBAL", "econ"],
  ["This House opposes the use of private military contractors in armed conflict", "GLOBAL", "war"],
  ["This House would end all arms sales to states engaged in active hostilities", "GLOBAL", "war"],
  ["This House believes that nuclear-armed states have a duty to adopt no-first-use policies", "GLOBAL", "war"],
  ["This House would establish universal jurisdiction for crimes against the environment", "GLOBAL", "env"],
  ["This House believes that reparations for colonialism should be paid to states rather than individuals", "GLOBAL", "ethics"],
  ["This House would return all colonial-era artefacts held in Western museums unconditionally", "GLOBAL", "culture"],
  ["This House believes that development aid should be replaced with unconditional cash transfers", "GLOBAL", "dev"],
  ["This House would make membership of international institutions conditional on democratic governance", "GLOBAL", "pol"],
  ["This House believes that the World Bank and the IMF should be dissolved", "GLOBAL", "econ"],
  ["This House would impose carbon tariffs on imports from high-emitting economies", "GLOBAL", "env"],
  ["This House believes that states should be liable for cyberattacks launched from their territory", "GLOBAL", "tech"],
  ["This House would create a single global patent regime for pharmaceuticals", "GLOBAL", "health"],
  ["This House believes that vaccine patents should be suspended during declared pandemics", "GLOBAL", "health"],
  ["This House would grant legal personhood to major rivers, forests and ecosystems", "GLOBAL", "env"],
  ["This House believes that the deep seabed should be closed to mining indefinitely", "GLOBAL", "env"],
  ["This House would tax international financial transactions to fund global public goods", "GLOBAL", "econ"],

  // --- Africa ---------------------------------------------------------------
  ["This House would dissolve the CFA franc", "AFR", "econ"],
  ["This House believes that the African Union should suspend members who extend presidential term limits", "AFR", "pol"],
  ["This House supports the African Continental Free Trade Area removing all agricultural tariffs", "AFR", "econ"],
  ["This House believes that African states should nationalise their critical mineral industries", "AFR", "econ"],
  ["This House regrets the reliance of African universities on foreign research funding", "AFR", "edu"],
  ["This House would make instruction in indigenous languages compulsory in African primary schools", "AFR", "edu"],
  ["This House believes that ECOWAS was right to threaten military intervention against coup leaders", "AFR", "pol"],
  ["This House would redirect African defence spending to agricultural subsidies", "AFR", "dev"],
  ["This House believes that mobile money has done more for African development than foreign aid", "AFR", "dev"],
  ["This House would grant communal land title rather than individual freehold in rural Africa", "AFR", "dev"],
  ["This House believes that African states should refuse debt restructuring that requires austerity", "AFR", "econ"],
  ["This House supports a continental free movement protocol with no visa requirements", "AFR", "mig"],
  ["This House regrets the growth of Pentecostal prosperity gospel movements in Africa", "AFR", "relig"],
  ["This House would ban foreign states from operating military bases on the African continent", "AFR", "war"],
  ["This House believes that the diaspora should be given voting rights in African national elections", "AFR", "pol"],
  ["This House would prioritise off-grid renewable generation over national grid expansion", "AFR", "env"],
  ["This House believes that traditional authorities should have no formal role in African governance", "AFR", "pol"],
  ["This House would legalise and tax artisanal mining", "AFR", "econ"],
  ["This House regrets the framing of Africa as a frontier market by international investors", "AFR", "econ"],
  ["This House believes that Nollywood and Afrobeats have done more for African soft power than diplomacy", "AFR", "culture"],
  ["This House would impose export taxes on unprocessed raw commodities", "AFR", "econ"],
  ["This House believes that African states should pursue regional currencies over national ones", "AFR", "econ"],
  ["This House would make climate adaptation, not mitigation, the priority of African climate policy", "AFR", "env"],
  ["This House supports compulsory national service for African university graduates", "AFR", "youth"],

  // --- Middle East & North Africa -------------------------------------------
  ["This House believes that Gulf states should abolish the kafala sponsorship system immediately", "MENA", "labour"],
  ["This House would end fuel subsidies across the Middle East and North Africa", "MENA", "econ"],
  ["This House believes that sovereign wealth funds should be barred from investing in foreign sport", "MENA", "sport"],
  ["This House regrets the use of megaprojects as a development strategy in the Gulf", "MENA", "dev"],
  ["This House believes that regional powers should normalise relations irrespective of human rights records", "MENA", "pol"],
  ["This House would make water allocation in the region subject to binding arbitration", "MENA", "env"],
  ["This House believes that religious courts should have no jurisdiction over family law", "MENA", "law"],
  ["This House supports quotas for women in Middle Eastern parliaments", "MENA", "gender"],
  ["This House would end conscription in the region", "MENA", "war"],
  ["This House believes that oil exporters should legislate a binding date to end extraction", "MENA", "env"],
  ["This House regrets the brain drain of Arab professionals to the Gulf", "MENA", "labour"],
  ["This House would grant citizenship to long-term migrant workers in Gulf states", "MENA", "mig"],
  ["This House believes that state-funded satellite broadcasters do more harm than good in the region", "MENA", "media"],
  ["This House supports secular constitutions across the Arab world", "MENA", "relig"],
  ["This House would prioritise reconstruction over accountability in post-conflict Arab states", "MENA", "war"],
  ["This House believes that regional universities should teach exclusively in Arabic", "MENA", "edu"],

  // --- Europe ---------------------------------------------------------------
  ["This House would abolish unanimity voting in the European Council", "EUR", "pol"],
  ["This House believes that the European Union should admit Ukraine on an accelerated timetable", "EUR", "pol"],
  ["This House would create a single European army under Commission command", "EUR", "war"],
  ["This House believes that the EU should condition structural funds on judicial independence", "EUR", "law"],
  ["This House would abolish agricultural subsidies under the Common Agricultural Policy", "EUR", "econ"],
  ["This House regrets the European Court of Human Rights ruling on climate obligations", "EUR", "law"],
  ["This House believes that European states should ban political advertising online entirely", "EUR", "media"],
  ["This House would introduce a four-day working week by statute", "EUR", "labour"],
  ["This House believes that European cities should be closed to private cars", "EUR", "urban"],
  ["This House would impose rent controls in every major European city", "EUR", "urban"],
  ["This House believes that European states should pay for the return of colonial-era human remains", "EUR", "culture"],
  ["This House would abolish inherited titles and remaining aristocratic privileges", "EUR", "pol"],
  ["This House believes that state funding of political parties should replace private donation", "EUR", "pol"],
  ["This House would require public broadcasters to be funded by general taxation rather than licence fees", "EUR", "media"],
  ["This House believes that the Schengen area should be suspended during migration surges", "EUR", "mig"],
  ["This House would grant voting rights in national elections to all long-term residents", "EUR", "mig"],
  ["This House believes that European universities should charge tuition fees", "EUR", "edu"],
  ["This House would ban the sale of new internal combustion vehicles immediately", "EUR", "env"],
  ["This House believes that nuclear power is indispensable to European decarbonisation", "EUR", "env"],
  ["This House would break up the largest European banks", "EUR", "econ"],
  ["This House regrets the professionalisation of European politics", "EUR", "pol"],
  ["This House would require all public sector algorithms to be open source", "EUR", "tech"],
  ["This House believes that European states should recognise a right to disconnect from work communications", "EUR", "labour"],
  ["This House would abolish the monarchy in all European states that retain one", "EUR", "pol"],
  ["This House believes that regional independence referendums should require a supermajority", "EUR", "pol"],
  ["This House would make voting compulsory", "EUR", "pol"],

  // --- North America --------------------------------------------------------
  ["This House would abolish the Electoral College", "NAM", "pol"],
  ["This House believes that Supreme Court justices should serve fixed terms", "NAM", "law"],
  ["This House would abolish qualified immunity for police officers", "NAM", "law"],
  ["This House believes that plea bargaining should be prohibited", "NAM", "law"],
  ["This House would cancel all federal student debt", "NAM", "edu"],
  ["This House believes that standardised testing should play no role in university admissions", "NAM", "edu"],
  ["This House would make healthcare entirely publicly funded", "NAM", "health"],
  ["This House believes that direct-to-consumer pharmaceutical advertising should be banned", "NAM", "health"],
  ["This House would abolish single-family zoning nationwide", "NAM", "urban"],
  ["This House believes that federal land should be transferred to indigenous nations", "NAM", "ethics"],
  ["This House would end the filibuster", "NAM", "pol"],
  ["This House believes that primary elections have damaged democratic representation", "NAM", "pol"],
  ["This House would prohibit corporate political spending outright", "NAM", "pol"],
  ["This House believes that college athletes should be employees of their universities", "NAM", "sport"],
  ["This House would impose a wealth tax on unrealised capital gains", "NAM", "econ"],
  ["This House believes that antitrust law should break up the largest technology firms", "NAM", "tech"],
  ["This House would repeal intermediary liability protections for social platforms", "NAM", "media"],
  ["This House believes that the jury system should be replaced with professional adjudication", "NAM", "law"],
  ["This House would decriminalise all drug possession", "NAM", "health"],
  ["This House believes that prisons should be abolished in favour of restorative alternatives", "NAM", "law"],
  ["This House would guarantee every citizen a job rather than a basic income", "NAM", "labour"],
  ["This House believes that local control of school funding should be abolished", "NAM", "edu"],
  ["This House would require ranked-choice voting in all federal elections", "NAM", "pol"],
  ["This House believes that gerrymandering should be resolved by independent commissions", "NAM", "pol"],
  ["This House would abolish tipping as a wage structure", "NAM", "labour"],
  ["This House believes that Canada should abandon supply management in agriculture", "NAM", "econ"],
  ["This House would make indigenous language education compulsory in Canadian schools", "NAM", "edu"],
  ["This House believes that medically assisted dying should be available for psychiatric suffering", "NAM", "ethics"],

  // --- Latin America --------------------------------------------------------
  ["This House would legalise and regulate the cocaine trade", "LAM", "law"],
  ["This House believes that Latin American states should prioritise sovereignty over trade liberalisation", "LAM", "econ"],
  ["This House supports a common Latin American currency", "LAM", "econ"],
  ["This House believes that militarised policing has failed in Latin America", "LAM", "law"],
  ["This House would grant land title to informal urban settlements", "LAM", "urban"],
  ["This House believes that Latin American states should reject extractive investment from any foreign power", "LAM", "env"],
  ["This House would make Amazon protection a condition of regional trade agreements", "LAM", "env"],
  ["This House believes that liberation theology was good for Latin America", "LAM", "relig"],
  ["This House would abolish presidential re-election across the region", "LAM", "pol"],
  ["This House supports constitutional recognition of plurinational statehood", "LAM", "pol"],
  ["This House would pay rainforest states not to extract", "LAM", "env"],
  ["This House believes that remittances have made Latin American states complacent", "LAM", "dev"],
  ["This House would nationalise lithium reserves", "LAM", "econ"],
  ["This House believes that truth commissions should name perpetrators even without trial", "LAM", "law"],
  ["This House would decriminalise abortion throughout the region", "LAM", "gender"],
  ["This House believes that conditional cash transfer programmes should become unconditional", "LAM", "dev"],
  ["This House would ban private security forces", "LAM", "law"],
  ["This House believes that Latin American states should default rather than accept IMF conditionality", "LAM", "econ"],

  // --- Caribbean ------------------------------------------------------------
  ["This House believes that Caribbean states should pursue reparations through litigation rather than diplomacy", "CARIB", "ethics"],
  ["This House would end citizenship-by-investment programmes", "CARIB", "econ"],
  ["This House believes that tourism dependence is the greatest threat to Caribbean sovereignty", "CARIB", "econ"],
  ["This House supports a single CARICOM market with free movement of labour", "CARIB", "econ"],
  ["This House would remove the British monarch as head of state in all remaining realms", "CARIB", "pol"],
  ["This House believes that climate finance should be delivered as grants, never loans, to small island states", "CARIB", "env"],
  ["This House would legalise cannabis cultivation for export", "CARIB", "econ"],
  ["This House believes that Caribbean states should abolish the Privy Council as final court of appeal", "CARIB", "law"],

  // --- South Asia -----------------------------------------------------------
  ["This House would abolish caste-based reservation in favour of economic criteria", "SAS", "ethics"],
  ["This House believes that India should adopt a uniform civil code", "SAS", "law"],
  ["This House would privatise state-owned banks in South Asia", "SAS", "econ"],
  ["This House believes that farm subsidies in South Asia should be replaced with direct income support", "SAS", "econ"],
  ["This House would make English the sole medium of instruction in South Asian higher education", "SAS", "edu"],
  ["This House believes that coaching culture has ruined South Asian education", "SAS", "edu"],
  ["This House would ban religious processions through contested neighbourhoods", "SAS", "relig"],
  ["This House believes that South Asian states should decriminalise defamation", "SAS", "media"],
  ["This House would impose a legal cap on wedding expenditure", "SAS", "culture"],
  ["This House believes that dynastic politics is the central failure of South Asian democracy", "SAS", "pol"],
  ["This House would end fuel and fertiliser subsidies despite the political cost", "SAS", "env"],
  ["This House believes that Bangladesh should prioritise climate relocation over sea defences", "SAS", "env"],
  ["This House would make river water sharing in the region subject to binding treaty arbitration", "SAS", "env"],
  ["This House believes that garment-sector buyers should be legally liable for factory conditions", "SAS", "labour"],
  ["This House would guarantee urban employment as India guarantees rural employment", "SAS", "labour"],
  ["This House believes that Sri Lanka was right to accept IMF conditionality", "SAS", "econ"],
  ["This House would abolish the first-past-the-post system in South Asian legislatures", "SAS", "pol"],
  ["This House believes that cricket boards have too much power over the national game", "SAS", "sport"],
  ["This House would legally recognise unpaid domestic labour in divorce settlements", "SAS", "gender"],
  ["This House believes that South Asian states should not pursue nuclear parity", "SAS", "war"],

  // --- East Asia ------------------------------------------------------------
  ["This House would pay citizens to have children", "EAS", "gender"],
  ["This House believes that East Asian states should open their borders to mass immigration to offset demographic decline", "EAS", "mig"],
  ["This House would abolish the national university entrance examination", "EAS", "edu"],
  ["This House believes that private tutoring should be banned outright", "EAS", "edu"],
  ["This House would legally cap working hours with criminal penalties for employers", "EAS", "labour"],
  ["This House believes that state-directed industrial policy has served East Asia well", "EAS", "econ"],
  ["This House would break up the family conglomerates that dominate East Asian economies", "EAS", "econ"],
  ["This House believes that Japan should abandon pacifism in its constitution", "EAS", "war"],
  ["This House would make eldercare a universal public entitlement funded by payroll taxes", "EAS", "health"],
  ["This House believes that East Asian states should prioritise rural revitalisation over urban growth", "EAS", "urban"],
  ["This House would impose statutory limits on screen time for minors", "EAS", "youth"],
  ["This House believes that the idol industry is incompatible with labour rights", "EAS", "culture"],
  ["This House would require algorithmic recommendation systems to be switchable off by default", "EAS", "tech"],
  ["This House believes that social credit mechanisms can be compatible with liberal governance", "EAS", "tech"],
  ["This House would abolish the household registration system", "EAS", "mig"],
  ["This House believes that East Asian states should pursue regional security guarantees independent of the United States", "EAS", "war"],
  ["This House would recognise dual citizenship", "EAS", "mig"],
  ["This House believes that cultural export subsidies are a legitimate instrument of foreign policy", "EAS", "culture"],

  // --- Southeast Asia -------------------------------------------------------
  ["This House would abandon the ASEAN principle of non-interference", "SEA", "pol"],
  ["This House believes that ASEAN should expel members that stage military coups", "SEA", "pol"],
  ["This House would ban the burning of agricultural land to end transboundary haze", "SEA", "env"],
  ["This House believes that Southeast Asian states should refuse to choose between the great powers", "SEA", "war"],
  ["This House would nationalise palm oil plantations", "SEA", "env"],
  ["This House believes that Southeast Asian states should legislate against royal defamation laws", "SEA", "law"],
  ["This House would move national capitals away from sinking coastal cities", "SEA", "urban"],
  ["This House believes that special economic zones have failed Southeast Asian workers", "SEA", "labour"],
  ["This House would impose a regional moratorium on new coal plants", "SEA", "env"],
  ["This House believes that migrant domestic workers should have the right to unionise", "SEA", "labour"],
  ["This House would make ride-hailing and delivery platforms employ their drivers", "SEA", "labour"],
  ["This House believes that Southeast Asian states should resolve maritime disputes through arbitration alone", "SEA", "war"],
  ["This House would end dynastic political families through constitutional bans", "SEA", "pol"],
  ["This House believes that tourism caps should be imposed on heritage sites", "SEA", "culture"],

  // --- Central Asia & the Caucasus -----------------------------------------
  ["This House believes that Central Asian states should diversify away from resource rents at any cost", "CAS", "econ"],
  ["This House would make regional water allocation binding on upstream states", "CAS", "env"],
  ["This House believes that Central Asian states should adopt the Latin alphabet", "CAS", "culture"],
  ["This House would prohibit labour migration agreements that bind workers to a single destination state", "CAS", "mig"],
  ["This House believes that the region should pursue neutrality rather than alliance", "CAS", "war"],
  ["This House would open the region to foreign ownership of agricultural land", "CAS", "econ"],
  ["This House believes that post-Soviet states should fully declassify their security service archives", "CAS", "pol"],

  // --- Oceania --------------------------------------------------------------
  ["This House would enshrine an indigenous advisory body in the constitution", "OCE", "pol"],
  ["This House believes that Australia should end all new fossil fuel extraction immediately", "OCE", "env"],
  ["This House would grant Pacific islanders unrestricted residence rights in Australia and New Zealand", "OCE", "mig"],
  ["This House believes that offshore processing of asylum seekers is indefensible", "OCE", "mig"],
  ["This House would return national parks to indigenous management", "OCE", "env"],
  ["This House believes that Pacific states should litigate climate obligations at the International Court of Justice", "OCE", "env"],
  ["This House would make treaty negotiation with indigenous nations legally binding on future governments", "OCE", "law"],
  ["This House believes that compulsory voting should be exported as a democratic reform", "OCE", "pol"],
  ["This House would ban gambling advertising entirely", "OCE", "health"],
  ["This House believes that deep-sea mining in the Pacific should be permanently prohibited", "OCE", "env"],

  // --- Artificial intelligence ---------------------------------------------
  ["This House would require that any system capable of generating media disclose that it did so", "GLOBAL", "ai"],
  ["This House believes that training a model on copyrighted work without licence is theft", "GLOBAL", "ai"],
  ["This House would make developers strictly liable for harms caused by their models", "GLOBAL", "ai"],
  ["This House believes that frontier model development should require a government licence", "GLOBAL", "ai"],
  ["This House would prohibit the use of automated decision-making in criminal sentencing", "GLOBAL", "ai"],
  ["This House believes that artificial intelligence should never be used in clinical diagnosis without a human signature", "GLOBAL", "ai"],
  ["This House would ban emotion recognition systems in workplaces and schools", "GLOBAL", "ai"],
  ["This House believes that model weights above a capability threshold should never be released publicly", "GLOBAL", "ai"],
  ["This House would tax firms for every job displaced by automation", "GLOBAL", "ai"],
  ["This House believes that students should be permitted to use generative tools in all assessed work", "GLOBAL", "ai"],
  ["This House would prohibit synthetic performances by deceased artists", "GLOBAL", "ai"],
  ["This House believes that the pursuit of artificial general intelligence should be paused by treaty", "GLOBAL", "ai"],
  ["This House would require public disclosure of the energy and water use of large training runs", "GLOBAL", "ai"],
  ["This House believes that companion systems for the lonely do more good than harm", "GLOBAL", "ai"],
  ["This House would give authors a statutory right to refuse the use of their work in training data", "GLOBAL", "ai"],

  // --- Technology, media and speech ----------------------------------------
  ["This House would ban social media for those under sixteen", "GLOBAL", "media"],
  ["This House believes that anonymity online should be abolished", "GLOBAL", "media"],
  ["This House would require platforms to offer a chronological feed by default", "GLOBAL", "media"],
  ["This House believes that the right to be forgotten should extend to journalism", "GLOBAL", "media"],
  ["This House would nationalise critical digital infrastructure", "GLOBAL", "tech"],
  ["This House believes that encryption backdoors are never justified", "GLOBAL", "tech"],
  ["This House would prohibit targeted advertising based on behavioural data", "GLOBAL", "media"],
  ["This House believes that journalists should never pay for information", "GLOBAL", "media"],
  ["This House would make newspapers charge for access rather than depend on advertising", "GLOBAL", "media"],
  ["This House believes that state-funded fact-checking is a threat to free expression", "GLOBAL", "media"],
  ["This House would ban facial recognition in public spaces", "GLOBAL", "tech"],
  ["This House believes that the open internet has failed as a civic project", "GLOBAL", "tech"],
  ["This House would treat access to the internet as a justiciable human right", "GLOBAL", "tech"],
  ["This House believes that whistleblowers who leak classified material should be immune from prosecution", "GLOBAL", "law"],
  ["This House would prohibit the private ownership of genetic databases", "GLOBAL", "tech"],
  ["This House believes that cryptocurrency should be banned as a payment instrument", "GLOBAL", "econ"],
  ["This House would require interoperability between all messaging services", "GLOBAL", "tech"],

  // --- Ethics and philosophy ------------------------------------------------
  ["This House believes that we owe future generations more than we owe the present poor", "GLOBAL", "ethics"],
  ["This House would prioritise the prevention of suffering over the creation of happiness", "GLOBAL", "ethics"],
  ["This House believes that moral obligations do not diminish with distance", "GLOBAL", "ethics"],
  ["This House regrets the professionalisation of charity", "GLOBAL", "ethics"],
  ["This House believes that it is wrong to bring a child into a warming world", "GLOBAL", "ethics"],
  ["This House would abolish inheritance", "GLOBAL", "ethics"],
  ["This House believes that forgiveness is overvalued", "GLOBAL", "ethics"],
  ["This House would permit the sale of organs by living donors", "GLOBAL", "ethics"],
  ["This House believes that animals should hold enforceable legal rights", "GLOBAL", "ethics"],
  ["This House would end the farming of animals for food", "GLOBAL", "ethics"],
  ["This House believes that punishment can never be justified by deterrence alone", "GLOBAL", "ethics"],
  ["This House would abolish the concept of desert from public policy", "GLOBAL", "ethics"],
  ["This House believes that a life of comfortable illusion is worse than a life of difficult truth", "GLOBAL", "ethics"],
  ["This House regrets the decline of shame as a social mechanism", "GLOBAL", "ethics"],
  ["This House believes that institutions should apologise for acts committed by their predecessors", "GLOBAL", "ethics"],
  ["This House would allow individuals to sell their vote", "GLOBAL", "ethics"],
  ["This House believes that paternalism is justified where people consistently act against their own interests", "GLOBAL", "ethics"],
  ["This House would place a legal duty on bystanders to rescue", "GLOBAL", "law"],

  // --- Health ---------------------------------------------------------------
  ["This House would make organ donation an opt-out system", "GLOBAL", "health"],
  ["This House believes that pandemic treaties should allow compulsory licensing of any medicine", "GLOBAL", "health"],
  ["This House would ration healthcare explicitly by quality-adjusted life years", "GLOBAL", "health"],
  ["This House believes that obesity should be treated as a disease rather than a behaviour", "GLOBAL", "health"],
  ["This House would tax ultra-processed food", "GLOBAL", "health"],
  ["This House believes that mental health treatment should be prioritised over physical health treatment at the margin", "GLOBAL", "health"],
  ["This House would licence parents of children with chronic conditions as paid carers", "GLOBAL", "health"],
  ["This House believes that pharmaceutical research should be funded by prizes rather than patents", "GLOBAL", "health"],
  ["This House would permit challenge trials in epidemics", "GLOBAL", "health"],
  ["This House believes that medical confidentiality should yield to public health surveillance", "GLOBAL", "health"],
  ["This House would make vaccination compulsory for school attendance", "GLOBAL", "health"],
  ["This House believes that assisted dying should be available on request to any competent adult", "GLOBAL", "health"],
  ["This House would ban the advertising of alcohol", "GLOBAL", "health"],
  ["This House believes that heritable human genetic modification should be permitted to prevent disease", "GLOBAL", "health"],
  ["This House would require health systems to disclose the cost of every treatment to the patient", "GLOBAL", "health"],

  // --- Gender, family and the household ------------------------------------
  ["This House would require equal, non-transferable parental leave for both parents", "GLOBAL", "gender"],
  ["This House believes that quotas are the only effective remedy for workplace inequality", "GLOBAL", "gender"],
  ["This House would abolish marriage as a legal category", "GLOBAL", "gender"],
  ["This House believes that surrogacy should be legal and paid", "GLOBAL", "gender"],
  ["This House would make domestic labour legally compensable within marriage", "GLOBAL", "gender"],
  ["This House believes that single-sex spaces should be defined by self-identification", "GLOBAL", "gender"],
  ["This House would fund fertility preservation as a public health service", "GLOBAL", "gender"],
  ["This House believes that the burden of care work is the central economic injustice of our time", "GLOBAL", "gender"],
  ["This House would criminalise coercive control", "GLOBAL", "law"],
  ["This House believes that anonymity should be granted to those accused of sexual offences until conviction", "GLOBAL", "law"],

  // --- Education and youth --------------------------------------------------
  ["This House would abolish private schools", "GLOBAL", "edu"],
  ["This House believes that homework should be abolished in primary education", "GLOBAL", "edu"],
  ["This House would teach philosophy from the first year of schooling", "GLOBAL", "edu"],
  ["This House believes that university should be free only for subjects of public need", "GLOBAL", "edu"],
  ["This House would replace examinations with continuous assessment", "GLOBAL", "edu"],
  ["This House believes that schools should not teach national history as a narrative of pride", "GLOBAL", "edu"],
  ["This House would lower the voting age to sixteen", "GLOBAL", "youth"],
  ["This House believes that children should have a legal right to refuse medical treatment", "GLOBAL", "youth"],
  ["This House would ban smartphones from schools entirely", "GLOBAL", "youth"],
  ["This House believes that parents should not post images of their children online", "GLOBAL", "youth"],
  ["This House would raise the age of criminal responsibility to sixteen", "GLOBAL", "youth"],
  ["This House believes that mandatory civic or military service strengthens democracies", "GLOBAL", "youth"],
  ["This House would make debate a compulsory part of the school curriculum", "GLOBAL", "edu"],
  ["This House believes that universities should divest from fossil fuels and arms manufacturers", "GLOBAL", "edu"],
  ["This House would abolish academic tenure", "GLOBAL", "edu"],
  ["This House believes that legacy admissions are a form of corruption", "GLOBAL", "edu"],

  // --- Labour and economics -------------------------------------------------
  ["This House would introduce an unconditional basic income", "GLOBAL", "labour"],
  ["This House believes that worker representation on company boards should be mandatory", "GLOBAL", "labour"],
  ["This House would cap executive pay as a multiple of the median wage", "GLOBAL", "labour"],
  ["This House believes that the right to strike should extend to essential services", "GLOBAL", "labour"],
  ["This House would abolish unpaid internships", "GLOBAL", "labour"],
  ["This House believes that remote work has weakened the labour movement", "GLOBAL", "labour"],
  ["This House would require firms to publish the pay of every employee", "GLOBAL", "labour"],
  ["This House believes that gig platforms should be required to recognise unions", "GLOBAL", "labour"],
  ["This House would replace corporation tax with a tax on land", "GLOBAL", "econ"],
  ["This House believes that central banks should target employment rather than inflation", "GLOBAL", "econ"],
  ["This House would abolish stock buybacks", "GLOBAL", "econ"],
  ["This House believes that economic growth should no longer be a goal of public policy", "GLOBAL", "econ"],
  ["This House would guarantee housing as a legal entitlement", "GLOBAL", "urban"],
  ["This House believes that short-term rental platforms should be banned in housing-scarce cities", "GLOBAL", "urban"],
  ["This House would make all public transport free at the point of use", "GLOBAL", "urban"],

  // --- Culture, sport, religion and space ----------------------------------
  ["This House would abolish copyright after the death of the author", "GLOBAL", "culture"],
  ["This House believes that public funding of the arts should go only to work that would not otherwise exist", "GLOBAL", "culture"],
  ["This House regrets the dominance of franchise cinema", "GLOBAL", "culture"],
  ["This House believes that artists should be judged separately from their conduct", "GLOBAL", "culture"],
  ["This House would repatriate human remains from all scientific collections", "GLOBAL", "culture"],
  ["This House believes that national teams should be open to anyone resident in the country", "GLOBAL", "sport"],
  ["This House would abolish national representation in the Olympic Games", "GLOBAL", "sport"],
  ["This House believes that sport should permit performance enhancement under medical supervision", "GLOBAL", "sport"],
  ["This House would ban heading in youth football", "GLOBAL", "sport"],
  ["This House believes that sports governing bodies should refuse hosting bids from authoritarian states", "GLOBAL", "sport"],
  ["This House would prohibit private ownership of football clubs", "GLOBAL", "sport"],
  ["This House believes that the state should not fund religious schools", "GLOBAL", "relig"],
  ["This House would tax religious institutions as ordinary businesses", "GLOBAL", "relig"],
  ["This House believes that religious exemptions from generally applicable laws should be abolished", "GLOBAL", "relig"],
  ["This House would prohibit the commercial exploitation of outer space resources", "GLOBAL", "space"],
  ["This House believes that crewed missions to Mars are an indefensible use of public money", "GLOBAL", "space"],
  ["This House would place satellite constellations under international licensing", "GLOBAL", "space"],
  ["This House believes that space agencies should be merged into a single international body", "GLOBAL", "space"],

  // --- Environment ----------------------------------------------------------
  ["This House would permit solar geoengineering research at scale", "GLOBAL", "env"],
  ["This House believes that carbon offset markets should be abolished", "GLOBAL", "env"],
  ["This House would impose personal carbon allowances", "GLOBAL", "env"],
  ["This House believes that climate activism is justified in breaking the law", "GLOBAL", "env"],
  ["This House would ban private jets", "GLOBAL", "env"],
  ["This House believes that degrowth is the only honest climate policy", "GLOBAL", "env"],
  ["This House would rewild a fifth of all agricultural land", "GLOBAL", "env"],
  ["This House believes that rich states should pay poor states to leave fossil reserves untouched", "GLOBAL", "env"],
  ["This House would make environmental impact a justiciable constitutional duty", "GLOBAL", "env"],
  ["This House believes that nuclear waste storage is a solved problem", "GLOBAL", "env"],

  // --- Migration ------------------------------------------------------------
  ["This House would open all borders", "GLOBAL", "mig"],
  ["This House believes that states should select migrants by economic contribution alone", "GLOBAL", "mig"],
  ["This House would allow asylum claims to be lodged from abroad", "GLOBAL", "mig"],
  ["This House believes that brain drain obliges destination states to compensate origin states", "GLOBAL", "mig"],
  ["This House would abolish immigration detention", "GLOBAL", "mig"],
  ["This House believes that citizenship should be earned through residence rather than birth", "GLOBAL", "mig"],
  ["This House would require new arrivals to settle in designated regions", "GLOBAL", "mig"],

  // --- Law and the state ----------------------------------------------------
  ["This House would abolish life imprisonment without parole", "GLOBAL", "law"],
  ["This House believes that constitutional courts should be able to strike down constitutional amendments", "GLOBAL", "law"],
  ["This House would make all criminal trials public and recorded", "GLOBAL", "law"],
  ["This House believes that sortition should replace elections for one legislative chamber", "GLOBAL", "pol"],
  ["This House would impose term limits on all elected office", "GLOBAL", "pol"],
  ["This House believes that referendums should never decide questions of rights", "GLOBAL", "pol"],
  ["This House would require citizens to pass a civics test before voting", "GLOBAL", "pol"],
  ["This House believes that political parties should be internally democratic by law", "GLOBAL", "pol"],
  ["This House would abolish the secret ballot in legislatures", "GLOBAL", "pol"],
  ["This House believes that emergency powers should expire automatically without renewed consent", "GLOBAL", "law"],
  ["This House would prohibit former ministers from working in industries they regulated", "GLOBAL", "pol"],
  ["This House believes that civil disobedience requires an acceptance of punishment", "GLOBAL", "ethics"],
];

// NSDA-style resolutions, phrased as they appear on the American circuit.
export const RESOLUTIONS = [
  ["Resolved: In the United States, colleges and universities ought not consider standardized tests in admissions", "NAM", "edu"],
  ["Resolved: The United States federal government should substantially increase its investment in public transit", "NAM", "urban"],
  ["Resolved: A just government ought to prioritize civil liberties over national security", "GLOBAL", "ethics"],
  ["Resolved: In a democracy, the public's right to know ought to outweigh an individual's right to privacy", "GLOBAL", "media"],
  ["Resolved: Wealthy nations have an obligation to provide development assistance to other nations", "GLOBAL", "dev"],
  ["Resolved: States ought to eliminate their nuclear arsenals", "GLOBAL", "war"],
  ["Resolved: Predictive policing is unjust", "NAM", "law"],
  ["Resolved: The United States should adopt a single-payer universal healthcare system", "NAM", "health"],
  ["Resolved: Economic sanctions ought not be used to achieve foreign policy objectives", "GLOBAL", "war"],
  ["Resolved: Public colleges and universities in the United States ought not restrict any constitutionally protected speech", "NAM", "edu"],
  ["Resolved: On balance, the benefits of genetic engineering outweigh the harms", "GLOBAL", "health"],
  ["Resolved: Countries ought to prohibit the production of nuclear power", "GLOBAL", "env"],
  ["Resolved: The United States federal government should substantially increase its protection of water resources", "NAM", "env"],
  ["Resolved: Developed countries have a moral obligation to mitigate the effects of climate change", "GLOBAL", "env"],
  ["Resolved: In the United States, the benefits of charter schools outweigh the harms", "NAM", "edu"],
  ["Resolved: Justice requires the recognition of animal rights", "GLOBAL", "ethics"],
  ["Resolved: The member states of the United Nations ought to eliminate their nuclear arsenals", "GLOBAL", "war"],
  ["Resolved: The United States ought to guarantee universal child care", "NAM", "gender"],
  ["Resolved: On balance, social media has been detrimental to democratic participation", "GLOBAL", "media"],
  ["Resolved: The United States should end its arms sales to foreign governments", "NAM", "war"],
  ["Resolved: In the United States, the practice of plea bargaining ought to be abolished", "NAM", "law"],
  ["Resolved: Artificial intelligence ought to be regulated as a public utility", "GLOBAL", "ai"],
  ["Resolved: The United States should substantially reduce its military presence in the Indo-Pacific", "NAM", "war"],
  ["Resolved: On balance, the rise of remote work has benefited workers in the United States", "NAM", "labour"],
  ["Resolved: States ought to recognize a legal right to housing", "GLOBAL", "urban"],
  ["Resolved: In the United States, universities ought to abolish legacy admissions", "NAM", "edu"],
  ["Resolved: Compulsory voting ought to be adopted in democratic states", "GLOBAL", "pol"],
  ["Resolved: On balance, standardized testing improves educational outcomes", "NAM", "edu"],
  ["Resolved: The World Trade Organization has done more harm than good", "GLOBAL", "econ"],
  ["Resolved: In the United States, the Supreme Court ought to be subject to term limits", "NAM", "law"],
  ["Resolved: Nations ought to prioritize adaptation over mitigation in their climate policy", "GLOBAL", "env"],
  ["Resolved: The United States should adopt a carbon tax", "NAM", "env"],
  ["Resolved: Individuals have a moral obligation to assist people in need", "GLOBAL", "ethics"],
  ["Resolved: In matters of collective defense, the United States ought to prioritize multilateralism", "NAM", "war"],
  ["Resolved: A just society ought not use intellectual property rights to restrict access to medicine", "GLOBAL", "health"],
  ["Resolved: The United States should substantially increase legal immigration", "NAM", "mig"],
  ["Resolved: On balance, algorithmic content curation harms minors", "GLOBAL", "youth"],
  ["Resolved: Governments ought to provide a universal basic income", "GLOBAL", "labour"],
  ["Resolved: In the United States, the electoral college ought to be abolished", "NAM", "pol"],
  ["Resolved: The right to strike ought to be protected for all public sector workers", "GLOBAL", "labour"],
];

export const ALL_TOPICS = MOTIONS.concat(RESOLUTIONS).map((t, i) => ({
  id: i,
  text: t[0],
  region: t[1],
  theme: t[2],
  style: t[0].startsWith("Resolved") ? "res" : "thw",
}));

export const TOPIC_COUNT = ALL_TOPICS.length;
